### ISSUE TITLE
Subscriptions testing

### ISSUE THREAD

**Issue by naptiv** [codefoundries/isomorphic-material-relay-starter-kit#101]
Opening two browser tab and playing with the todo should update both pages, I guess that's because of the in-memory data storage ? 

As Cassendra is not Heroku friendly, maybe implementing [Waterline](https://github.com/balderdashy/waterline) would be a good idea to deal with the hosting and testing issue ?

**Comment by thelordoftheboards** [comment]
@naptiv I do not believe this is a current feature of Relay. If you look at the commits there is some work done on subscriptions, but when is it going to be complete is anyone's guess since Facebook does not issue a roadmap.
I did look at waterline some time ago and I was very unhappy with the quality of the integration with Cassandra. I was having trouble running even simple examples. Do you know any examples online of using Cassandra with Waterline?

**Comment by naptiv** [comment]
Ok, http://graphql.org/blog/subscriptions-in-graphql-and-relay/

Actually, how would you build a real time notification system ?

I'll try to find the cassandra adapter for waterline.

**Comment by thelordoftheboards** [comment]
Very clearly I am behind the curve on this one. I will start reading.
As for waterline, I experimented with: https://github.com/dtoubelis/sails-cassandra
I could not find any working examples of any significant complexity, and the whole experience of trying to put the pieces together was not pleasant. Maybe the situation has changed (just like with subscriptions?).

**Comment by thelordoftheboards** [comment]
I created a separate issue https://github.com/codefoundries/isomorphic-material-relay-starter-kit/issues/107 in order to track the subscriptions separately from the data persistence. Also, I intend to integrate dataloader - https://github.com/codefoundries/isomorphic-material-relay-starter-kit/issues/69
That would have to be able to work with the data persistence as well.

**Comment by thelordoftheboards** [comment]
Since this issue now is split in two, I am closing it.
