### ISSUE TITLE
Could someone explain why seq-queue is needed?

### ISSUE THREAD

**Issue by joonhocho** [codefoundries/isomorphic-material-relay-starter-kit#116]
> I am more irked by the fact that the network layer injection is a global, hence the whole queue thing

I am new to relay and don't understand what is meant by 'network layer injection is a global, hence the whole queue thing'.

I looked at the source and found the use of seq-queue to wrap around each request to be handled in serial mode.
I am afraid that the use of serial queue will slow down QPS as each request handling will be blocking the next request. Afaik, It basically kills the asynchronous nature of node/javascript.

Could someone explain why the queue is needed to resolve which problem?

**Comment by thelordoftheboards** [comment]
Indeed only one server rendering can run at a time in this version. The queue is used to ensure the network layer to be the same for the duration of the server rendering. The network layer contains the user information:

```javascript
  const headers = { };
  if( req.cookies.auth_token )
    headers.Cookie = 'auth_token=' + req.cookies.auth_token;
  headers.user_auth_token = process.env.USER_AUTH_SECRET;
.........
Relay.injectNetworkLayer( new Relay.DefaultNetworkLayer( GRAPHQL_URL, { headers: headers } ) );
```

So, for a solution where initial loads of the pages (server render) are relatively less frequent than graphql requests from using the application as an SPA, the hack above could be satisfactory. If server renders are more prevalent, it would not be.
Since facebook is actively working on full isomorphic support for Relay, I did not invest any additional effort into the subject. Once Relay proper is isomorphic, we can simply remove the queue.

**Comment by joonhocho** [comment]
I see. Thank you for the answer!
