### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by terrisgit** [codefoundries/isomorphic-material-relay-starter-kit#33]
Text translation is often done late in a project, resulting in a large amount of tedious work and bugs. Starter kits should show developers how to begin projects the 'right' way.

There are many tools and techniques for text translation aka I18N. I have tried several over a period of 30 years in multiple programming languages. For example, I have used GNU gettext. I find text auto-extractors to be error-prone.

I have had good experience with counterpart: https://github.com/martinandert/counterpart .

I tried react-translate-component. I found it to be too limiting as I could not use it to set props. However, react-translate-component could be dropped into any project that uses counterpart. In fact, I discovered counterpart via react-translate-component.

If the following looks acceptable, I will take your additional feedback and create a PR. Thank you.

# In package.json add:

```
  "counterpart": "^0.17.1",
```

# Create locale/en.js

```
module.exports = {
  application: {
    name: 'IMRSK'
  }
};
```

# In webapp/app.js add:

```
var counterpart = require ('counterpart');
...
counterpart.registerTranslations('en', require('../locale/en'));
...
counterpart.setLocale('en);
```

counterpart.setLocale can be called again later more intelligently. The user could choose a locale or it could be chosen via http headers.

# To retrieve translated strings

```
var counterpart = require('counterpart');
...
{ counterpart.translate('application.name') }
```

**Comment by thelordoftheboards** [comment]
@terrisgit this sounds like an awesome addition! And indeed embedding it early rather than late is an obvious plus.
I am not familiar with the advantages or disadvantages of the different options so I will take your word on it.
I have a question - how will the user change the locale? Will it be a little flag in the title bar? And how will the choice be saved? Should it be part of the routers, like `http://localhost/en/ToDo/any` for English and `http://localhost/es/ToDo/any` for Spanish? Or is it rather a cookie thing?

**Comment by terrisgit** [comment]
Those are all good questions. The good news is you can defer them. What you need to address early on is avoiding hard-coding english throughout the menu items, text prompts, etc.. I can gradually help to move the strings into locale files. 

The initial locale should be based on incoming http headers. The user's preference setting should be stored in the User table. It is common to put a flag icon in the application's main menu because navigating to a "user preferences" section sometimes requires being able to read text. For example, such an icon would appear in the login dialog. This icon invokes a submenu containing all of the locales to choose from.

By the way, the locale folder is at the root rather than webapp due to the graphql server. We could however have two folders, one under webapp and one under server. I could use your advice there. What about the REST service that you use for login?

**Comment by nodkz** [comment]
According to Search Engine Optimization it should  be different urls for different languages.

BTW Cookie is worst solution, because in some EU countries people block them.

**Comment by nodkz** [comment]
Also take a look on https://github.com/yahoo/react-intl/issues/162 another intl library. Version 2.0.0-beta* with cool react components.

**Comment by terrisgit** [comment]
react-intl does look better. Someone needs to figure out how to set/choose the locale based on the route without breaking route configuration.

**Comment by thelordoftheboards** [comment]
The cookies seem to be at disadvantage when it comes to SEO and I would really like to keep this kit SEO friendly. After all it's one of the two big benefits of isomorphism together with the speed increase for first load.

I would not worry about the cookie being blocked - we are requiring cookies for the authentication after all. The SEO argument stays, so let's say cookies are out.

I added a note to add locale to the User type. However, I would like to be able to support anonymous users too, so the user record is not a solution, but rather a way to override whatever information is retrieved from header.

I assume some kind of combination of express middleware together with routing would resolve the issue with routing, so that once the locale is resolved, all the rest of the routes works as they currently do.

react-intl v2 seems pretty cool. The passing of the locale to the component could be done fairly easily, I am sure it can live at the top level of `Chrome.jsx`, right under `<IsomorphicRouter.Router routes={routes} history={browserHistory} />`.

**Comment by thelordoftheboards** [comment]
Added `User_IsAnonymous` and `User_Locale` in https://github.com/codefoundries/isomorphic-material-relay-starter-kit/commit/7de4d1bc869bca75115644d939d18deea9a5ba9d

```javascript
type Viewer implements Node {
  id: ID!
  User_IsAnonymous: Boolean
  User_DisplayName: String
  User_ProfilePhoto: String
  User_Email: String
  User_Locale: String
  compendiums(after: String, first: Int, before: String, last: Int): CompendiumsConnection
  ToDos(status: String = "any", after: String, first: Int, before: String, last: Int): ToDosConnection
  ToDo_TotalCount: Int
  ToDo_CompletedCount: Int
}
```

**Comment by thelordoftheboards** [comment]
I recently added a small popover for the logged in users. It has the user name, profile pic, (nonfunctioning) menu items for editing profile and settings, and login as a different user and log out.
I could add a language as a little icon inside there:

![image](https://cloud.githubusercontent.com/assets/7056535/12692393/38366488-c6ab-11e5-8170-4ba4e6d28803.png)

That said, this is currently available only to signed in users.

I could also add a little flag icon on the most right, which would be available both to signed in, as well as anonymous users.

Opinions?

**Comment by thelordoftheboards** [comment]
So, a small icon to the right it is, independent of the currently logged in user:

![image](https://cloud.githubusercontent.com/assets/7056535/12694679/96a215a0-c6ea-11e5-9ac1-066902b25791.png)

I believe this is the correct approach since it allows for the anonymous users to change the language. Maybe, if a user has already logged in and chosen the language, the icon would be hidden and moved to the user properties to save space, but this is task for another time.

For the time being the code does not really do anything other than display pictures of flags.

**Comment by babylon05** [comment]
Seems like the best approach to me. What do you think about displaying the avatar/profile pic on the menu bar for an authenticated user instead of the (full) human bust?

**Comment by thelordoftheboards** [comment]
I'm not sure I understand. You mean have:

![image](https://cloud.githubusercontent.com/assets/7056535/12698744/abed3542-c759-11e5-8d19-10ea3291e65b.png)

Instead of:

![image](https://cloud.githubusercontent.com/assets/7056535/12698747/b6abb7d8-c759-11e5-9552-a56fedc5b97e.png)

?

**Comment by babylon05** [comment]
Yes

**Comment by thelordoftheboards** [comment]
The navigation bar is currently implemented as:

http://www.material-ui.com/#/components/toolbar

The components shown to work on the bar are Drop Down Menu, Font Icon, Icon Menu and Raised Button. In order to implement the To Do active badge with number, I used:

http://www.material-ui.com/#/components/badge

If you look closely there are still some issues  related to the size, and it causes the other icons in the navigation bar to move around. For this reason, I suspect that using the

http://www.material-ui.com/#/components/avatar

in the navigation bar might be non trivial. I might be completely wrong of course. You are more than welcome to try and PR if it works well. I definitely think it would be a better UI design, my only concern is the effort required to implement it. If you like to try it, I suggest to create a separate issue too, since it is not directly related to the translation.

**Comment by terrisgit** [comment]
+5000

**Comment by terrisgit** [comment]
I don't have enough experience with react-intl v2. Can it be used with pure NodeJS code e.g., GraphQL server?

**Comment by thelordoftheboards** [comment]
If I only knew .... one way to find out I guess?

**Comment by thelordoftheboards** [comment]
Repository with example of using translation: https://github.com/ngduc/react-setup

**Comment by thelordoftheboards** [comment]
Will not be done for this project.
