### ISSUE TITLE
Force login

### ISSUE THREAD

**Issue by terrisgit** [codefoundries/isomorphic-material-relay-starter-kit#36]
Force the display of the login dialog if the user hits particular routes (e.g., display TODOs) if no one is logged in.

**Comment by thelordoftheboards** [comment]
For some use cases, ToDos being a good example probably, items can only be viewed by authenticated users. If a user is not authenticated, they should not see ToDos.

I would also like to support a use case similar to, let's say, Linked In profile.

* Anonymous viewing is allowed and some information is displayed.
* Authenticated users, if they have some kind of relationship with the owner of the profile, can be shown more information.

In order to support both the ToDo use case, and profile use case I suggest the following:

* Provide a property on the User object called `Authenticated`. It's a boolean indicating whether there is a user being authenticated or not.
* For the ToDo use case:
** The GraphQL server will know that the user is anonymous and will return no records.
** The client-side React component for ToDo will read the User's property `Authenticated`, and if it is false, will display a log in dialog.
* For the profile use case:
** The GraphQL server will provide as much detail as the current user should receive, anonymous (public profile) or authenticated (possibly more detailed profile).
** The client-side React component will simply display what is provided by GraphQL. If the user wants to see more details, they can log in.

How does the above sound as a general approach?

**Comment by thelordoftheboards** [comment]
Closed it by mistake

**Comment by thelordoftheboards** [comment]
Can be implemented on the user profile page, for instance

**Comment by thelordoftheboards** [comment]
Force log in on user password change and user profile

**Comment by thelordoftheboards** [comment]
Example will be added in https://github.com/codefoundries/isomorphic-material-relay-starter-kit/issues/202
